trigger:
  - master

pr:
 branches:
   include:
     - master

variables:
  solutionFile : '$(Build.SourcesDirectory)\src\azure-functions-util.sln'
  configuration: 'release'

pool:
  vmImage: 'windows-latest'

steps:
- task: NuGetToolInstaller@1
  displayName: Install NuGet Client
  inputs:
    checkLatest: true

- task: SonarCloudPrepare@1
  inputs:
    SonarCloud: 'SonarCloud-CloudNDevOps'
    organization: 'cloudndevops'
    scannerMode: 'MSBuild'
    projectKey: 'Newtonsoft.Extensions'
    projectName: 'Newtonsoft.Extensions'
    extraProperties: 'sonar.cs.vstest.reportsPaths=$(System.DefaultWorkingDirectory)/TestResults/**/*.coverage'

- task: DotNetCoreCLI@2
  displayName: Restore NuGet Packages
  inputs:
    command: restore
    projects: $(solutionFile)

- task: DotNetCoreCLI@2
  displayName: Build Solution
  inputs:
    command: build
    projects: $(solutionFile)
    configuration: $(configuration)
    arguments: --no-restore

- task: DotNetCoreCLI@2
  displayName: Execute Test Cases
  inputs:
    command: test
    projects: $(solutionFile)
    configuration: $(configuration)
    nobuild: true
    arguments: --collect:"Code Coverage"

- task: SonarCloudAnalyze@1
  displayName: SonarQube Analysis

- task: SonarCloudPublish@1
  displayName: Publish to SonarCloud
  
- task: DotNetCoreCLI@2
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
  displayName: Create NuGet Package
  inputs:
   command: pack
   projects: $(solutionFile)
   configuration: $(configuration)
   nobuild: true

- task: NuGetCommand@2
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
  displayName: Publish NuGet Package and Symbols to NuGet.org
  inputs:
    command: 'push'
    packagesToPush: '$(Build.ArtifactStagingDirectory)/**/*.nupkg;!$(Build.ArtifactStagingDirectory)/**/*.symbols.nupkg'
    nuGetFeedType: 'external'
    publishFeedCredentials: 'NuGet - CloudNDevOps.Newtonsoft.Extensions'
